title: Lisa Hanzl
email: lisa.hanzl@uni-due.de
description: Doctoral Researcher at Universität Duisburg-Essen
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lisahanzl
github_username:  lisahanzl
linkedin_username: lisa-hanzl-351288b2
author_display: false

nav_ext_links:
  - name: CV
    url: https://lisahanzl.github.io/assets/CV_Lisa_Hanzl_EN_2022.pdf
    
remote_theme: gaalcaras/academic
plugins:
  - jekyll-feed
