title: Lisa Hanzl
email: lisa.hanzl@icloud.com
description: Doctoral Researcher at Universität Duisburg-Essen
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lisahanzl
github_username:  lisahanzl
author_display: true

nav_ext_links:
  - name: CV
    url: https://lisahanzl.github.io/assets/CV_Lisa_Hanzl_2023.pdf
    
remote_theme: gaalcaras/academic
plugins:
  - jekyll-feed
